[package]
name = "sequencer_new"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
lazy_static = "1.4.0"
rocksdb = "0.22.0"
bitcoincore-rpc = "0.19.0"
